In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("/content/online_retail_II.xlsx")

In [ ]:
data.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom

In [ ]:
data.size

4203688

In [ ]:
data.shape

(525461, 8)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  525461 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [ ]:
data.isnull().sum() #checking for null values

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [ ]:
data[data["Customer ID"].isnull()]
data[data["Description"].isnull()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
524730,538141,22218,NaN,2,2010-12-09 15:58:00,0.0,NaN,United Kingdom
524731,538143,84534B,NaN,1,2010-12-09 15:58:00,0.0,NaN,United Kingdom
525231,538159,21324,NaN,-18,2010-12-09 17:17:00,0.0,NaN,United Kingdom
525232,538158,20892,NaN,-32,2010-12-09 17:17:00,0.0,NaN,United Kingdom
525233,538160,20956,NaN,288,2010-12-09 17:18:00,0.0,NaN,United Kingdom

Observation: Missing descriptions occur in transactions that can include negative quantities and zero prices. Therefore, missing descriptions should not automatically be treated as ordinary missing product names without further investigation.

In [ ]:
data["Description"].fillna("Unknown")

0         15CM CHRISTMAS GLASS BALL 20 LIGHTS
1                          PINK CHERRY LIGHTS
2                         WHITE CHERRY LIGHTS
3                RECORD FRAME 7" SINGLE SIZE
4              STRAWBERRY CERAMIC TRINKET BOX
                         ...
525456                   FELTCRAFT DOLL ROSIE
525457           FELTCRAFT PRINCESS LOLA DOLL
525458         FELTCRAFT PRINCESS OLIVIA DOLL
525459     PINK FLORAL FELTCRAFT SHOULDER BAG
525460                 JUMBO STORAGE BAG SUKI
Name: Description, Length: 525461, dtype: object

In [ ]:
data.isnull().sum() #checking for null values

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(6865)

In [ ]:
data.drop_duplicates(inplace = True)

In [ ]:
data.shape

(518596, 8)

In [ ]:
print("Total Customers: ",len(data["Customer ID"].unique()))

Total Customers:  4384

In [ ]:
print("Total Products(Unique): ",len(data["StockCode"].unique()))

Total Products(Unique):  4632

In [ ]:
print("Total Countries(Unique): ",data["Country"].nunique())

Total Countries(Unique):  40

In [142]:
print("Total Canceled Transactions: ", data["Invoice"].str.startswith("C").sum())

Total Canceled Transactions:  10182

In [ ]:
start_date = data["InvoiceDate"].min()
end_date = data["InvoiceDate"].max()
print(f"Start Date: {start_date}")
print(f"End Date: {end_date}")

Start Date: 2009-12-01 07:45:00
End Date: 2010-12-09 20:01:00

Phase 2

In [ ]:
#Determine the total revenue generated by the business, then identify the products that generate the most revenue.

In [130]:
#total revenue generated by the business
data["Revenue"] = data["Price"] * data["Quantity"]
revenue_total = data["Revenue"].sum()
print(f"Total Revenue :{revenue_total:.2f}")

Total Revenue :9505775.56

In [136]:
# identify the products that generate the most revenue.
data.groupby(["StockCode", "Description"]).Revenue.sum().sort_values(ascending = False)

StockCode     Description
22423         REGENCY CAKESTAND 3 TIER              162885.71
85123A        WHITE HANGING HEART T-LIGHT HOLDER    155540.37
DOT           DOTCOM POSTAGE                        116401.99
84879         ASSORTED COLOUR BIRD ORNAMENT          72251.32
22086         PAPER CHAIN KIT 50'S CHRISTMAS         57808.25
                                                      ...
D             Discount                               -7788.32
M             Manual                                -14137.84
BANK CHARGES  Bank Charges                          -26318.03
AMAZONFEE     AMAZON FEE                            -39243.08
B             Adjust bad debt                      -136552.02
Name: Revenue, Length: 5070, dtype: float64

In [ ]:
#How much of the revenue calculation comes from cancelled transactions, and how does total revenue change if cancellations are excluded?

In [161]:
cancelled_tra_total = data.loc[data["Invoice"].astype(str).str.startswith("C"), "Revenue"].sum()
print(f"Total Revenue of cancelled transactions :{cancelled_tra_total:.2f}")

Total Revenue of cancelled transactions :-629435.08

In [171]:
print(F"Revenue after excluding cancellations:  { revenue_total - abs(cancelled_tra_total):.2F}")

Revenue after excluding cancellations:  8876340.48